name: 'Gradle Version Incrementer'
description: 'Increments the version of a Gradle project'
inputs:
  latest_release:
    description: 'The latest version of the project'
    required: true
  actual_version:
    description: 'The actual version of the project'
    required: true
outputs:
  new_version:
    description: 'The new version of the project'
runs:
  using: 'node16'
  main: 'index.js'